name: Go Build releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            arch: arm64
            goos: linux
            goarch: arm64
          - os: macos-latest
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: macos-latest
            arch: arm64
            goos: darwin
            goarch: arm64
          - os: windows-latest
            arch: amd64
            goos: windows
            goarch: amd64
          - os: windows-latest
            arch: arm64
            goos: windows
            goarch: arm64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            $Env:GOOS="${{ matrix.goos }}"
            $Env:GOARCH="${{ matrix.goarch }}"
            go build -o output-${{ matrix.goos }}-${{ matrix.goarch }}
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o output-${{ matrix.goos }}-${{ matrix.goarch }}
          fi
        shell: bash


      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: output-${{ matrix.goos }}-${{ matrix.goarch }}
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
